import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '@/components/layout'
import TopChatRow from './TopChatRow'
// TopChatRow

const Home: NextPage = () => {
//  const key = process.env.MY_LAST_CHAT_ID;
  return (
    <Layout>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Top</h1>
      <hr />
      <TopChatRow ></TopChatRow>
    </div>
    </Layout>
  )
}

export default Home
