import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '@/components/layout'

const TestPage: React.FC = function () {

  const play = async function() {
//    const sound = document.querySelector<HTMLInputElement>('#notify_sound');
    const sound = document.querySelector<HTMLAudioElement>('#notify_sound');
    // @ts-ignore
    await sound.play();
    
  }

  return (
    <Layout>
    <div className="container test_wrap">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Test</h1>
      <hr />
      <audio className="notify_audio" src="/notify.mp3" id="notify_sound"
       controls>
      </audio>
      <hr />
      <button onClick={() => play()}>[ Play ]</button>

      <style>{`
      .test_wrap .notify_audio{ display: none ;}
      `}</style>
    </div>
    </Layout>
  )
}
export default TestPage;
